# Generated by Django 5.1.3 on 2024-12-02 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CensusTract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fips_code', models.CharField(max_length=10, unique=True)),
                ('shape_data', models.JSONField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fips_code', models.CharField(max_length=10, unique=True)),
                ('shape_data', models.JSONField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetropolitanArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cbsa_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField()),
                ('male', models.DecimalField(decimal_places=2, max_digits=100)),
                ('female', models.DecimalField(decimal_places=2, max_digits=100)),
                ('black', models.DecimalField(decimal_places=2, max_digits=100)),
                ('white', models.DecimalField(decimal_places=2, max_digits=100)),
                ('asian', models.PositiveIntegerField(default=0)),
                ('hispanic', models.PositiveIntegerField(default=0)),
                ('household_type', models.CharField(blank=True, max_length=255, null=True)),
                ('medean_income', models.IntegerField()),
                ('fips_code', models.CharField(max_length=12, unique=True)),
                ('shape_data', models.JSONField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('census_tract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.censustract')),
            ],
        ),
        migrations.AddField(
            model_name='censustract',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.county'),
        ),
        migrations.AddField(
            model_name='county',
            name='metropolitan_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.metropolitanarea'),
        ),
    ]
