# Generated by Django 5.1.3 on 2024-12-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='fips_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
