# Generated by Django 5.1.3 on 2024-12-01 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_metropolitanarea_counties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metropolitanarea',
            name='fips_codes',
        ),
        migrations.AddField(
            model_name='county',
            name='metropolitan_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counties', to='app.metropolitanarea'),
        ),
        migrations.DeleteModel(
            name='Counties',
        ),
    ]
