# Generated by Django 5.1.3 on 2024-12-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_county_fips_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockgroup',
            name='asian',
        ),
        migrations.RemoveField(
            model_name='blockgroup',
            name='hispanic',
        ),
        migrations.AddField(
            model_name='blockgroup',
            name='medean_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockgroup',
            name='medean_income',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
