# Generated by Django 5.1.3 on 2024-12-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_blockgroup_asian_remove_blockgroup_hispanic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockgroup',
            old_name='medean_age',
            new_name='median_age',
        ),
        migrations.RenameField(
            model_name='blockgroup',
            old_name='medean_income',
            new_name='median_income',
        ),
    ]
