# Generated by Django 5.1.3 on 2024-12-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_medean_age_blockgroup_median_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censustract',
            name='fips_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
